* Title

* Abstract
A max 150-word description of the project question or idea, goals, dataset used. What story you would like to tell and why? What's the motivation behind your project?

This repository will go over a fairy tale database and try to look at discrepancies in gender. 

* Research questions
A list of research questions you would like to address during the project.

* Dataset
List the dataset(s) you want to use, and some ideas on how do you expect to get, manage, process and enrich it/them. Show you've read the docs and are familiar with some examples, and you've a clear idea on what to expect. Discuss data size and format if relevant.

Link to the dataset: https://www.hlt.inesc-id.pt/w/Fairy_tale_corpus

* A tentative list of milestones for the project
Add here a sketch of your planning for the coming weeks. Please mention who does what.

* Documentation
This can be added as the project unfolds. You should describe, in particular, what your repo contains and how to reproduce your res
